/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VeduMessage = IDL.Record({
  'id' : IDL.Nat,
  'skipQuestions' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
  'hasCallback' : IDL.Bool,
  'intent' : IDL.Text,
  'details' : IDL.Opt(IDL.Text),
  'externalEndpoint' : IDL.Opt(IDL.Text),
  'nextQuestion' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getAllMessages' : IDL.Func([], [IDL.Vec(VeduMessage)], ['query']),
  'getBookingSteps' : IDL.Func(
      [],
      [IDL.Record({ 'flowIndex' : IDL.Nat, 'questions' : IDL.Vec(IDL.Text) })],
      [],
    ),
  'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(VeduMessage)], ['query']),
  'getVeduData' : IDL.Func(
      [],
      [
        IDL.Record({
          'messages' : IDL.Vec(VeduMessage),
          'bookingQuestions' : IDL.Vec(VeduMessage),
        }),
      ],
      ['query'],
    ),
  'initializeMessages' : IDL.Func([], [], []),
  'processBookingResponse' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'completed' : IDL.Bool,
          'summary' : IDL.Opt(IDL.Text),
          'nextQuestion' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'startBookingSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'submitBooking' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Text], []),
  'submitSingleBooking' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VeduMessage = IDL.Record({
    'id' : IDL.Nat,
    'skipQuestions' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
    'hasCallback' : IDL.Bool,
    'intent' : IDL.Text,
    'details' : IDL.Opt(IDL.Text),
    'externalEndpoint' : IDL.Opt(IDL.Text),
    'nextQuestion' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getAllMessages' : IDL.Func([], [IDL.Vec(VeduMessage)], ['query']),
    'getBookingSteps' : IDL.Func(
        [],
        [
          IDL.Record({
            'flowIndex' : IDL.Nat,
            'questions' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(VeduMessage)], ['query']),
    'getVeduData' : IDL.Func(
        [],
        [
          IDL.Record({
            'messages' : IDL.Vec(VeduMessage),
            'bookingQuestions' : IDL.Vec(VeduMessage),
          }),
        ],
        ['query'],
      ),
    'initializeMessages' : IDL.Func([], [], []),
    'processBookingResponse' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'completed' : IDL.Bool,
            'summary' : IDL.Opt(IDL.Text),
            'nextQuestion' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'startBookingSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'submitBooking' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Text], []),
    'submitSingleBooking' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };